version: "3"

services:
  client:
    build: ./client/
    container_name: "client"
    depends_on:
      - gateway-client
    ports:
      - 81:80
    restart: always
  manager:
    build: ./manager/
    container_name: "manager"
    depends_on:
      - gateway-manager
    ports:
      - 82:80
    restart: always
  gateway-client:
    build: ./services/rxjava-gateway/gateway-client/target/docker-bin/
    container_name: "gateway-client"
    depends_on:
      - center
      - config
    environment:
      CENTER_HOST: center:8761
  gateway-manager:
    build: ./services/rxjava-gateway/gateway-manager/target/docker-bin/
    container_name: "gateway-manager"
    depends_on:
      - center
      - config
    environment:
      CENTER_HOST: center:8761
  service-goods:
    build: ./services/rxjava-service/service-goods/target/docker-bin/
    container_name: "service-goods"
    depends_on:
      - config
      - center
      - mongodb
      - redis
    environment:
      DB_HOST: mongodb:27017
      CENTER_HOST: center:8761
  service-user:
    build: ./services/rxjava-service/service-user/target/docker-bin/
    container_name: "service-user"
    depends_on:
      - config
      - mongodb
      - redis
      - center
    environment:
      DB_HOST: mongodb:27017
      CENTER_HOST: center:8761
  center:
    build: ./services/center/target/docker-bin/
    container_name: "center"
    depends_on:
      - config
    expose:
      - 8761
    ports:
      - 8761:8761
  config:
    build: ./services/config/target/docker-bin/
    container_name: "config"
    expose:
      - 8888
    ports:
      - 8888:8888
  mongodb:
    image: 'registry.cn-beijing.aliyuncs.com/rxjava/mongo:3.7.3-jessie'
    container_name: "mongodb"
    ports:
      - 27018:27017
    restart: always
  redis:
    image: 'registry.cn-beijing.aliyuncs.com/rxjava/redis:4.0.4-alpine'
    container_name: "redis"
    ports:
      - 6380:6379
    restart: always
